# Generated by Django 6.0.4 on 2026-05-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_product_alter_member_email_alter_member_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
