# Generated by Django 6.0.4 on 2026-05-02 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_member_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2026, 5, 2)),
        ),
    ]
